#!/bin/bash
# 
# Simple Pomodoro style timer for Bash.
# Defaults to 1500 seconds (25 minutes)
# Enter the number of seconds you need.
# -------------------------------------
function delay {
	clear
	row=1
	col=2
	echo "delay is ${T}"
	for ((i = T; i >= 0; i--)) {
		tput cup $row $col
		echo -ne "$i\033[0K\r"
		sleep 1
	}
}

function alert {
	notify-send -t 0 'Take a break!'
	paplay /usr/share/sounds/freedesktop/stereo/complete.oga
	sleep 1
	spd-say "Just what do you think you are doing, Dave? Take a short break."
}

function main {
	T=${1:-1500}
	delay
	alert
}

main $1


